learning_log/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/',include('users.urls')),#Добавим строку для включения файла urls .py из users. Эта строка будет соответ- ствовать любому URL-адресу, начинающемуся со слова users, например http:// localhost:8000/users/login/
    path('',include('learning_logs.urls')),
    
]

learning_logs/urls.py
#Определяет схемы URL для learning_logs.
from django.urls import path #импортируется функция path, она необходима для связывания URL с представлениями 

from . import views #точка приказывает Python импортировать представления из каталога, в котором находится текущий модуль urls .py

app_name = 'learning_logs'#Переменная app_name помогает Django отличить этот файл urls .py от одноименных файлов в других приложениях в проекте 
 
urlpatterns = [ #Переменная urlpatterns в этом модуле представляет собой список страниц, которые могут запрашиваться из приложения learning_logs
    # Домашняя страница
    path('', views.index, name='index'),
    # Страница со списком всех тем.
    path('topics/',views.topics,name='topics'),
    # Когда Django проверяет запрашиваемый URL-адрес, эта схема совпадет с любым URL-адресом, 
    # который состоит из базового URL-адреса и слова topics. Слеш в конце можно включить, а можно не включать, 
    # но после слова topics ничего быть не должно, иначе схема не совпадет. Любой запрос с URL-адресом, 
    # соответствующим этой схеме, будет передан функции topics() в views .py.
    
    # Страница с подробной информацией по отдельной теме
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    # Вторая часть строки, /<int:topic_id>/, описывает целое число, заключенное между двумя слешами; 
    # это целое число сохраняется в аргу- менте topic_id.
    #Когда Django находит URL-адрес, соответствующий этой схеме, вызывается функция представления topic(), 
    # в аргументе которой передается значение, хранящееся в topic_id.
    
    path('new_topic/',views.new_topic,name='new_topic'),
    path('new_entry/<int:topic_id>/',views.new_entry,name='new_entry'),
    path('edit_entry/<int:entry_id>/',views.edit_entry,name='edit_entry')
]

users/urls.py
#Определяет схемы URL для пользователей

from django.urls import path,include
from . import views

#Сначала импортируется функция path, а затем функция include для включения аутентификационных URL-адресов 
# по умолчанию, определенных Django. Эти URL- адреса по умолчанию включают именованные схемы, такие как 
# 'login' и 'logout'. Переменной app_name присваивается значение 'users', чтобы инфраструктура Django могла 
# отличить эти URL-адреса от URL-адресов, принадлежащих другим приложениям. Даже URL-адреса по умолчанию, 
# предоставляемые Djano, при включении в файл urls .py приложения users будут доступны через пространство 
# имен users. Схема страницы входа соответствует URL http://localhost:8000/users/login/ . 
# Когда Django читает этот URL-адрес, слово users указывает, что следует обратиться к users/urls .py, 
# а login сообщает о том, что запросы должны отправляться представлению login по умолчанию.
app_name='users'
urlpatterns = [
    # Включить URL авторизации по умолчанию.
    path('',include('django.contrib.auth.urls')),
    # Страница регистрации.
    path('register/',views.register,name='register')
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
#Модель сообщает Django, как работать с данными, которые будут храниться в приложении. 

class Topic(models.Model):
    #Тема, которую изучает пользователь
    text=models.CharField(max_length=200) #Атрибуты CharField могут использоваться для хранения небольших объемов текста: имен, заголовков, названий городов и т. д. При определении атрибута CharField необходимо сообщить Django, сколько места нужно зарезер- вировать для него в базе данных. В данном случае задается максимальная длина max_length, равная 200 символам;
    date_added=models.DateTimeField(auto_now_add=True)#Атрибут date_added содержит данные DateTimeField — блок данных для хранения даты и времени. Аргумент auto_add_now=True приказывает Django автоматически присвоить этому атрибуту текущую дату и время каждый раз, когда пользователь создает новую тему.
    owner=models.ForeignKey(User,on_delete=models.CASCADE) # добавляется поле owner, используемое в отношении внешнего ключа к модели User. Если пользователь удаляется, все темы, связанные с этим пользователем, также будут удалены.
    
    def __str__(self):
        #Возвращает строковое представление модели.
        return self.text

class Entry(models.Model):
    topic=models.ForeignKey(Topic,on_delete=models.CASCADE)#topic, является экземпляром ForeignKey. Термин внешний ключ (foreign key) происходит из теории баз данных; внешний ключ содержит ссылку на другую запись в базе данных. Аргумент on_delete=models.CASCADE сообщает Django, что при удалении темы все записи, связанные с этой темой, также должны быть удалены
    text=models.TextField()
    date_added=models.DateTimeField(auto_now_add=True)
    
    class Meta: #класс Meta вкладывается в класс Entry. Класс Meta хранит дополнительную информацию по управлению моделью; в данном случае он позволяет задать специальный атрибут, который приказывает Django использовать форму мно- жественного числа Entries при обращении более чем к одной записи.
        verbose_name_plural='entries'
        
    def __str__(self): #Метод __str__() сообщает Django, какая информация должна отображаться при обращении к отдельным записям. Так как запись может быть достаточно длинным блоком текста, мы приказываем Django выводить только первые 50 символов
        """Возвращает строковое представление модели."""
        return f"{self.text[:50]}..."

learning_logs/forms.py
from django import forms
from .models import Topic,Entry

class TopicForm(forms.ModelForm):# определяется класс с именем TopicForm, наследующий от forms. ModelForm.
    class Meta: #ModelForm состоит из вложенного класса Meta, который сообщает Django, на какой модели должна базироваться форма и какие поля на ней должны находиться.
        model=Topic #форма создается на базе модели Topic
        fields=['text'] #на ней размещается только полеtext
        labels={'text':''} #приказывает Django не генерировать подпись для текстового поля
        
class EntryForm(forms.ModelForm):
    class Meta:
        model=Entry
        fields=['text']
        labels={'text':'Entry:'}
        widgets={'text':forms.Textarea(attrs={'cols':80})} 
        # включается атрибут widgets. Виджет (widget) представляет собой элемент формы HTML: однострочное 
        # или многострочное текстовое поле, раскрываю- щийся список и т. д. Включая атрибут widgets, 
        # вы можете переопределить виджеты, выбранные Django по умолчанию. Приказывая Django использовать 
        # элемент forms. Textarea, мы настраиваем виджет ввода для поля 'text', чтобы ширина текстовой 
        # области составляла 80 столбцов вместо значения по умолчанию 40. У пользователя будет достаточно 
        # места для создания содержательных записей.
        
        

learning_logs/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render,redirect
from django.urls import reverse
from .models import Topic,Entry
from .forms import TopicForm,EntryForm
from django.contrib.auth.decorators import login_required
from django.http import Http404 #мы импортируем исключение Http404, которое будет выдаваться программой при запросе пользователем темы, которую ему видеть не положено.

# Create your views here.
# Создайте здесь свои представления.

def index(request):
    #Домашняя страница приложения Learning Log
    return render(request,'learning_logs/index.html')

#Сначала импортируется функция login_required(). Мы применяем login_ required() как декоратор для функции представления topics(), для чего перед именем login_required() ставится знак @; он сообщает Python, что этот код должен выполняться перед кодом topics().
#Код login_required() проверяет, вошел ли пользователь в систему, и Django за- пускает код topics() только при выполнении этого условия. Если же пользователь не выполнил вход, он перенаправляется на страницу входа.
#Чтобы перенаправление работало, необходимо внести изменения settings .py и сообщить Django, где искать страницу входа.
@login_required
#Функция topics() должна получать данные из базы данных и отправлять их шаблону.
def topics(request): #Функции topics() необходим один параметр: объект request, полученный Django от сервера 
    #Выводит список тем.
    topics=Topic.objects.filter(owner=request.user).order_by('date_added') #выдается запрос к базе данных на получение объектов Topic, отсортированных по атрибуту date_added
    #Если пользователь выполнил вход, в объекте запроса устанавливается атрибут request.user с информацией о пользователе. Фрагмент кода Topic.objects. filter(owner=request.user) приказывает Django извлечь из базы данных только те объекты Topic, у которых атрибут owner соответствует текущему пользователю.
    context={'topics':topics}#определяется контекст, который будет передаваться шаблону
    return render(request,'learning_logs/topics.html',context)#использующей данные, функции render() передается переменная context, а также объект request и путь к шаблону

#Представление отдельной темы
#Функция topic() должна получить тему и все связанные с ней записи из базы данных
@login_required
def topic(request,topic_id):
    #Выводит одну тему и все ее записи.
    topic=Topic.objects.get(id=topic_id)
    # Проверка того, что тема принадлежит текущему пользователю.
    if topic.owner!=request.user: #Если тема не принадлежит текущему пользователю, выдается исключение Http404, а Django возвращает страницу с ошибкой 404.
        raise Http404
    entries=topic.entry_set.order_by('-date_added') #знак «минус» перед date_added сортирует результаты в обратном порядке, то есть самые последние записи будут находиться на первых местах.
    context={'topic':topic,'entries':entries} #Тема и записи сохраняются в словаре context, который передается шаблону topic .html
    return render(request,'learning_logs/topic.html',context)

# Функция new_topic() должна обрабатывать две разные ситуации: исходные запросы страницы new_topic 
# (в этом случае должна отображаться пустая форма) и обработка данных, отправленных на форме. 
# Затем она должна перенаправить пользователя обратно на страницу topics:
@login_required
def new_topic(request):
    #Определяет новую тему.
    if request.method!='POST': #Если метод запроса отличен от POST, вероятно, используется запрос GET, поэтому необходимо вернуть пустую форму (даже если это запрос другого типа, это все равно безопасно)
        #Данные не отправлялись; создается пустая форма
        form=TopicForm() #Мы создаем экземпляр TopicForm, сохраняем его в переменной form и отправляем форму шаблону в словаре context
        #Так как при создании TopicForm аргументы не передавались, Django создает пустую форму, которая заполняется пользователем.
    else: #Если используется метод запроса POST, выполняется блок else, который обрабатывает данные, отправленные в форме
        #Отправлены данные POST; обработать данные.
        form=TopicForm(data=request.POST) #создаем экземпляр TopicForm и передаем ему данные, введенные пользователем, хранящиеся в request.POST.
        #Отправленную информацию нельзя сохранять в базе данных до тех пор, пока она не будет проверена. 
        # Функция is_valid() проверяет, что все обязательные поля были заполнены (все поля формы по умолчанию 
        # являются обязательными), а вве- денные данные соответствуют типам полей — например, 
        # что длина текста меньше 200 символов, как было указано в файле models .py в главе 18. 
        # Автоматическая проверка избавляет нас от большого объема работы. Если все данные действительны, 
        # можно вызвать метод save() , который записывает данные из формы в базу данных.
        if form.is_valid():
            new_topic = form.save(commit=False) # Save topic in a variable. При первом вызове form.save() передается аргумент commit=False, потому что новая тема должна быть изменена перед сохранением в базе данных
            new_topic.owner = request.user # Set topics owner attribute to current user. Атрибуту owner новой темы присваивается текущий пользователь
            new_topic.save() # Save the changes to the database.
            return HttpResponseRedirect(reverse('learning_logs:topics'))
            #form.save()
            #return redirect('learning_logs:topics') #После того как данные будут сохранены, страницу можно покинуть. Мы используем вызов redirect() для перенаправления браузера на страницу topics, на которой пользователь увидит только что введенную им тему в общем списке тем
    # Вывести пустую или недействительную форму.
    context={'form':form}
    return render(request,'learning_logs/new_topic.html',context)

@login_required
def new_entry(request,topic_id):
    #Добавляет новую запись по конкретной теме.
    topic=Topic.objects.get(id=topic_id)
    
    if request.method!='POST':
        #Данные не отправлялись; создается пустая форма.
        form=EntryForm()
    else:
        #Отправлены данные POST; обработать данные.
        form=EntryForm(data=request.POST)
        if form.is_valid():
            new_entry=form.save(commit=False)
            new_entry.topic=topic
            new_entry.save()
            # При вызове save() мы включаем аргумент commit=False для того, чтобы создать новый объект записи 
            # и сохранить его в new_entry, не сохраняя пока в базе данных. Мы присваиваем атрибуту topic объекта 
            # new_entry тему, прочитанную из базы данных в начале функции, после чего вызываем save() 
            # без аргументов. В результате запись сохраняется в базе данных с правильно ассоциированной темой.
            return redirect('learning_logs:topic',topic_id=topic_id)
            #Вызов redirect() получает два аргумента — имя представления, которому передается управление, 
            # и аргумент для функции представления. В данном случае происходит перенаправление функции topic(), 
            # которой должен переда- ваться аргумент topic_id. Вызов перенаправляет пользователя на страницу темы, 
            # для которой была создана запись, и пользователь видит новую запись в списке записей.
    # Вывести пустую или недействительную форму.
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)    

@login_required
def edit_entry(request,entry_id):
    #Редактирует существующую запись.
    entry=Entry.objects.get(id=entry_id)
    topic=entry.topic
    
    if topic.owner != request.user:
        raise Http404
    
    if request.method!='POST':
        #Исходный запрос; форма заполняется данными текущей записи.
        form=EntryForm(instance=entry)
        #В блоке if, который выполняется для запроса GET, создается экземпляр EntryForm с аргументом 
        # instance=entry. Этот аргумент приказывает Django создать форму, заранее заполненную информацией из 
        # существующего объекта записи. Пользова- тель видит свои существующие данные и может отредактировать их.
    else:
        #Отправка данных POST; обработать данные.
        form=EntryForm(instance=entry,data=request.POST)
        #При обработке запроса POST передаются аргументы instance=entry и data=request.POST. Они приказывают 
        # Django создать экземпляр формы на основании информации существующего объекта записи, обновленный 
        # данными из request.POST.
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic',topic_id=topic.id)
    
    # Если отображается исходная форма для редактирования записи или если отправленная форма недействительна, 
    # создается словарь context, а страница строится на базе шаблона edit_entry.html.
    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)

        
        
    

    
    
    

learning_logs/templates/learning_logs/base.html
{% load bootstrap4 %} <!--загружается коллекция шаблонных тегов из django-bootstrap4.-->

<!DOCTYPE html> <!--Затем файл объявляется как документ HTML-->
<html lang="en"> <!--написанный на английском языке-->
 <head> <!--Файл HTML состоит из двух основных частей, заголовка и тела; заголовок файла начинается здесь-->
  <!--Заголовок файла HTML не содержит контента: он всего лишь передает браузеру информацию, необходимую для правильного отображения страницы.-->
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1,
     shrink-to-fit=no">
   <title>Learning Log</title>
   {% bootstrap_css %}
   <!--используется один из шаблонных тегов django-bootstrap4, который приказывает Django включить все стилевые файлы Bootstrap. Следующий тег активизирует все интерактивное поведение, которое может использоваться на странице, например раздвижные навигационные панели-->
   {% bootstrap_javascript jquery='full' %}
</head>
<body> <!--открывающий тег <body> . Тело файла HTML содержит кон- тент, который будет виден пользователям на странице.-->
  <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
    <!--элемент <nav> обозначает раздел навигационных ссылок на странице. Весь контент внутри этого элемента 
      оформляется по правилам Bootstrap, определяемым селекторами navbar, navbar-expand-md и другим перечисленным 
      здесь. Селектор определяет, к каким элементам страницы должно применяться стилевое правило. 
      Селекторы navbar- light и bg-light оформляют навигационную панель темой со светлым фоном. Сокращение mb 
      в mb-4 происходит от «margin-bottom», то есть «нижнее поле»; этот селектор гарантирует, что между 
      навигационной панелью и остальным контентом страницы остается свободное место. Селектор border создает тонкую 
      рамку вокруг светлого фона, чтобы немного отделить его от остального контента страницы.-->

    <a class="navbar-brand" href="{% url 'learning_logs:index'%}">
        Learning Log</a>
    <!--задается имя проекта, которое выводится у левого края навигационной панели, и создается ссылка на домашнюю 
      страницу; она будет отображаться на каждой странице проекта. Селектор navbar-brand оформляет эту ссылку так, 
      чтобы она выделялась на фоне остальных ссылок; это оформление становится одной из составляющих фирменной символики сайта.-->

    <button class="navbar-toggler" type="button" data-toggle="collapse"
        data-target="#navbarCollapse" aria-controls="navbarCollapse"
        aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span></button>
      <!--шаблон определяет кнопку, которая будет отображаться, если ширины окна браузера не хватает для 
        горизонтального отображения всей навигационной панели. Когда пользователь нажимает кнопку, навигационные 
        элементы выводятся в раскрывающемся списке. Атрибут collapse сворачивает навигационную панель при 
        уменьшении размеров окна браузера и при отображении сайта на мобильных устройствах с малыми экранами.-->
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'learning_logs:topics'%}">
                  Topics</a></li>
          </ul>
          <ul class="navbar-nav ml-auto"> <!--ml-auto означает «margin- left-automatic», то есть «автоматическое левое поле»; этот селектор анализирует другие элементы на навигационной панели и определяет величину левого поля, которое сдвигает эту группу ссылок к правому краю экрана.-->
            {% if user.is_authenticated %}
              <li class="nav-item">
                <span class="navbar-text">Hello, {{ user.username }}.</span>
          </li>

          <form style= class="nav-item" method="post" action="{% url 'users:logout' %}">
            {% csrf_token %}
            <button class="nav-link" type="submit">Log out</button>
          </form>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:register' %}">Register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:login' %}">Log in</a></li>
        {% endif %}
        </ul>
      </div>
    </nav>
    <main role="main" class="container"> <!--Элемент main используется для основного контента в теле страницы. В данном случае назначается селектор container, что является простым способом группировки элементов на странице. В этот контейнер будут включены два элемента div.-->
      <div class="pb-2 mb-2 border-bottom">
        <!--содержит блок page_header. Мы будем использовать этот блок для отображения заголовка большинства 
          страниц. Чтобы секция выделялась на фоне других частей страницы, мы разместим отступы под заголовком. 
          Отступ (padding) представляет собой пространство между контентом элемента и его границей. 
          Селектор pb-2 — директива Bootstrap, создающая отступы умеренной величины в нижней части оформляемого 
          элемента. Полем (margin) называется пространство между границей элемента и другими элементами страницы. 
          В нашем приложении граница нужна только в нижней части страницы, поэтому мы используем селектор 
          border-bottom, создающий тонкую границу в нижней части блока page_header.-->
        {% block page_header %}{% endblock page_header %}
      </div>
      <div>
        {% block content %}{% endblock content %}
      </div>
    </main>
  </body>
</html>




<!--old base.html-->

{#<p>#}
    {#<a href="{% url 'learning_logs:index' %}">Learning Log</a> -#}
    <!--Learning Log</a> шаблонный тег {% url 'learning_logs:index' %} гене- рирует URL-адрес, соответствующий схеме URL, определенной в файле learning_ logs/urls .py с именем 'index'-->
    <!--В данном примере learning_logs — пространство имен, а index — схема URL с уникальным именем в этом пространстве имен
     Пространство имен определяется значением, присвоенным app_name в файлеlearning_logs/urls .py.-->
    {#<a href="{% url 'learning_logs:topics' %}">Topics</a>#}
    {#{% if user.is_authenticated %} <!--В системе аутентификации Django в каждом шаблоне доступна переменная user, которая всегда имеет атрибут is_authenticated: атрибут равен True, если пользователь прошел проверку, и False в противном случае. Это позволяет вам выводить разные сообщения для проверенных и непроверенных пользователей.-->#}
      {#Hello, {{user.username}}.#}
      {#<form method='post' action="{% url 'users:logout' %}"><!--https://stackoverflow.com/questions/77690729/django-built-in-logout-view-method-not-allowed-get-users-logout-->#}
        {#{% csrf_token %}#}
        {#<button type="submit">logout</button>#}
      {#</form>#} 
    {#{% else %}#}
      {#<a href="{% url 'users:register' %}">Register</a> -#}
      {#<a href="{% url 'users:login' %}">log in</a>#}
    {#{% endif %}#}
{#</p>#}
{#{% block content %}{% endblock content %}<!-- Блок с именем content резервирует место; информация, попадающая в блок content, будет определяться дочерним шаблоном.-->#}

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}

<p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>
  <p>Edit entry:</p>
  <form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post'>
    <!--аргумент action отправляет форму функции edit_entry() для обработ- ки. Идентификатор записи включается как аргумент в тег {url} , чтобы функция представления могла изменить правильный объект записи.-->
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">save changes</button>
  </form>
{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block page_header %} {#мы сообщаем Django о том, что далее следует определение содержимого блока page_header.#}
<div class='jumbotron'> {#Селектор jumbotron применяет эту группу стилевых директив из библиотеки Bootstrap к элементу.#}
    {#джамботронома — большого блока, который выдается на общем фоне страницы и может содержать любую информацию на ваше усмотрение. Обычно этот элемент используется на домашних страницах для размещениякраткого описания проекта.#}
    <h1 class="display-3">Track your learning.</h1> {#с селектором display-3 заголовок становится более тонким и высоким#}
    <p class="lead">Make your own Learning Log, and keep a list of the
        topics you're learning about. Whenever you learn something new
        about a topic, make an entry summarizing what you've learned.</p>
    <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}"
        role="button">Register &raquo;</a> {#Код &raquo; является сущностью HTML, представляющей две правые угло- вые скобки (>>).#}
  </div>
{% endblock page_header %} {#блок page_header закрывается. Контент на эту страницу добавляться не будет, поэтому определять блок content на этой странице не нужно.#}


<!--old index.html-->
{#{% extends "learning_logs/base.html" %}#}

{#{% block content %}#}
{#<p>Learning Log helps you keep track of your learning, for any topic you're#}
{#learning about.</p>#}
{#{% endblock content %}#}

<!--вставкой тега block с именем content. Все, что не наследуется от родительского шаблона, попадает 
    в блок content. В данном случае это абзац с описанием проекта Learning Log.  мы сообщаем о том, 
    что определение content завершено, при помощи тега endblock content. Наличие имени у endblock 
    не обязательно, но если шаблон увеличится и станет вклю- чать несколько блоков, будет полезно сразу видеть, 
    какой именно блок завершается.-->
    

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}
{% block content %}
  <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p> <!--выводится тема, чтобы пользователь мог видеть, в какую тему добавляется новая запись. Тема также служит ссылкой на главную страницу этой темы.-->
  <p>Add a new entry:</p>
  <form action="{% url 'learning_logs:new_entry' topic.id %}" method='post'> <!--Аргумент action формы включает значение topic_id из URL, чтобы функция пред- ставления могла связать новую запись с правильной темой-->
    {% csrf_token %}
    {{ form.as_p }}
    <button name='submit'>add entry</button>
  </form>
{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html'%}

{% block page_header %}
  <h3>{{ topic }}</h3>
{% endblock page_header %}

{% block content %}
<p>
    <a href="{% url 'learning_logs:new_entry' topic.id %}">Add new entry</a>
</p>

    {% for entry in entries %}
    <div class="card mb-3"> {#элемент с селектором card. Он имеет два вложенных элемента: первый предназначен для хранения временной метки и ссылки для редактирования, а второй — для хранения тела записи.#}
        <h4 class="card-header">
          {{ entry.date_added|date:'M d, Y H:i' }}
          <small><a href="{% url 'learning_logs:edit_entry' entry.id %}">
              edit entry</a></small>
        </h4>
        <div class="card-body">
          {{ entry.text|linebreaks }}
        </div>
      </div>
    {% empty %} <!--{ empty } используется для вывода сообщения об отсутствии записей.-->
    <p>There are no entries for this project yet.</p>
    {%endfor%}

{%endblock content%}


<!--old topic.html-->
{#{% extends 'learning_logs/base.html'%}#}

{#{% block content %}#}
<!--выводится текущая тема из шаблонной переменной {{ topic }}. Переменная topic доступна, потому что она включена в словарь context-->
{#<p>Topic: {{ topic }}</p>#} 
{#<p>Entries: </p>#}
{#<p>#}
    {#<a href="{% url 'learning_logs:new_entry' topic.id %}">add new entry</a>#}
{#</p>#}
{#<ul>#}
    {#{% for entry in entries %}#}
    {#<li>#}
        {#<p>{{ entry.date_added|date:'M d, Y H:i'}}</p> <!--В шаблонах Django вертикальная черта (|) представляет фильтр — функцию, изменяющую значение шаблонной переменной. Фильтр date:'M d, Y H:i' выводит временные метки в формате January 1, 2018 23:00. -->#}
        {#<p>{{ entry.text|linebreaks}}</p><!-- linebreaks следит за тем, чтобы длинный текст содержал разрывы строк в формате, поддерживаемом браузером (вместо блока непрерывного текста).-->#}
        {#<p>#}
            {#<a href="{% url 'learning_logs:edit_entry' entry.id %}">Edit entry</a>#}
        {#</p>#}
    {#</li>#}
    {#{% empty %} <!--{ empty } используется для вывода сообщения об отсутствии записей.-->#}
    {#<li>There are no entries for this project yet.</li>#}
    {#{%endfor%}#}
{#</ul>#}
{#{%endblock content%}#}